name: Verify PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip ci' ) }}
    uses: cloud-native-toolkit/action-workflows/.github/workflows/verify-gitops-module.yaml@v1
    with:
      testcase: ocp4_latest_gitops_cp4d
    secrets:
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GIT_ORG: ${{ secrets.GIT_ORG }}
      AWS_CLUSTER_USERNAME: ${{ secrets.AWS_CLUSTER_USERNAME }}
      AWS_CLUSTER_PASSWORD: ${{ secrets.AWS_CLUSTER_PASSWORD }}
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      GIT_ADMIN_USERNAME: ${{ secrets.GIT_ADMIN_USERNAME }}
      GIT_ADMIN_TOKEN: ${{ secrets.GIT_ADMIN_TOKEN }}
      CP_ENTITLEMENT_KEY: ${{ secrets.CP_ENTITLEMENT_KEY }}


  verifyMetadata:
    uses: cloud-native-toolkit/action-workflows/.github/workflows/verify-module-metadata.yaml@v1
